
VERSION 0.6

all:
  BUILD +verify
  BUILD +docker

verify:
  BUILD +lint
  BUILD +typecheck
  BUILD +npm-audit

deps:
  FROM ../node16+base
  WORKDIR /app
  COPY package-lock.json ./
  ENV npm_config_cache=/var/cache/npm
  RUN --mount=type=cache,target=/var/cache/npm npm ci --ignore-scripts
  IF [ "$USERPLATFORM" = "$TARGETPLATFORM" ]
    SAVE ARTIFACT ./node_modules AS LOCAL ./node_modules
  END
  COPY . .

build:
  FROM +deps
  RUN npm run build
  SAVE ARTIFACT ./dist AS LOCAL ./dist

deps-prod:
  FROM ../node16+base
  WORKDIR /app
  COPY package.json package-lock.json ./
  ENV npm_config_cache=/var/cache/npm
  RUN --mount=type=cache,target=/var/cache/npm npm ci --ignore-scripts --prod
  COPY . .

pulumi-deps:
  FROM docker.io/library/alpine:3.14.3@sha256:635f0aa53d99017b38d1a0aa5b2082f7812b03e3cdb299103fe77b5c8a07f1d2
  RUN wget https://github.com/pulumi/pulumi/releases/download/v3.20.0/pulumi-v3.20.0-linux-x64.tar.gz && \
      tar -xzvf ./pulumi-v3.20.0-linux-x64.tar.gz
  SAVE ARTIFACT ./pulumi

# TODO: az, gcloud, doctl CLIs

docker:
  FROM +deps-prod
  COPY +build/dist /app/dist
  ENTRYPOINT ["/bin/sh"]
  SAVE IMAGE --push afriel/infra:latest

npm-audit:
  FROM +deps
  RUN npx audit-ci

lint:
  FROM +deps
  RUN npm run lint

typecheck:
  FROM +deps
  RUN npm run typecheck
